"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['csc321.py']

OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    options={'csc321': OPTIONS},
)
